### ISSUE TITLE
Add tracking for ShareProvider

### ISSUE THREAD

**Issue by 2fd** [decentraland/decentraland-gatsby#454]
use hook: `useTrackContext`

Track all the following events:

- [x] `share`: each time a native share is triggered + data shared
- [x] `share_popup_open`: each time the share popup opens
- [x] `share_popup_close`: each time the share popup closes
- [x] `share_fallback`: each time a user clicks on twitter/facebook + data shares + which social network was used
